# Generated by Django 3.0.8 on 2020-08-20 09:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0004_auto_20200819_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopindex',
            options={'verbose_name': 'workshops'},
        ),
        migrations.AddField(
            model_name='workshop',
            name='page_stream',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='strapline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopindex',
            name='blurb',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopindex',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_images', to='home.Workshop')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
