# Generated by Django 3.0.8 on 2020-08-20 17:03

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200820_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='page_stream',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
