# Generated by Django 3.1.1 on 2020-09-29 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0009_auto_20200928_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitionimage',
            name='creator',
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=500, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to=settings.AUTH_USER_MODEL)),
                ('artwork_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('artwork_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='home.exhibition')),
            ],
        ),
    ]
