# Generated by Django 3.1.1 on 2020-09-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('home', '0011_soundbite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundbite',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_soundbite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
        migrations.AddField(
            model_name='soundbite',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='soundbite',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.artwork'),
        ),
    ]
