# Generated by Django 3.1.1 on 2020-09-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200929_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundbite',
            options={},
        ),
        migrations.RemoveField(
            model_name='soundbite',
            name='sort_order',
        ),
    ]
