# Generated by Django 3.1.1 on 2020-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200929_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artwork_soundbite',
            new_name='artwork_soundbites',
        ),
        migrations.RemoveField(
            model_name='soundbite',
            name='page',
        ),
        migrations.AddField(
            model_name='soundbite',
            name='name',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
