# Generated by Django 3.1.1 on 2020-09-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200929_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_soundbites',
        ),
        migrations.AddField(
            model_name='soundbite',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_soundbites', to='home.artwork'),
        ),
    ]
