# Generated by Django 3.1.1 on 2020-09-29 18:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0022_auto_20200929_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='page',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='room',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='Soundbite',
        ),
        migrations.AddField(
            model_name='exhibitionartwork',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.artwork'),
        ),
        migrations.AddField(
            model_name='exhibitionartwork',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artworks', to='home.exhibition'),
        ),
    ]
