# Generated by Django 3.1.1 on 2020-09-29 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('home', '0023_auto_20200929_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('room', models.CharField(max_length=500)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_media', to='home.exhibition')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='exhibitionartwork',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='exhibitionartwork',
            name='page',
        ),
        migrations.AddField(
            model_name='exhibitionimage',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhibitionimage',
            name='room',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='ExhibitionArtwork',
        ),
    ]
