# Generated by Django 3.1.1 on 2020-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200930_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionmedia',
            name='room',
            field=models.CharField(default='room 1', max_length=500),
            preserve_default=False,
        ),
    ]
