# Generated by Django 3.1.1 on 2020-09-30 21:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('home', '0026_exhibitionmedia_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('room_name', models.TextField(blank=True, null=True)),
                ('strapline', models.TextField(blank=True, null=True)),
                ('blurb', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='exhibitionimage',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='exhibitionimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='exhibitionmedia',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='exhibitionmedia',
            name='room',
        ),
    ]
