# Generated by Django 3.1.1 on 2020-09-30 21:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200930_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_images', to='home.room'),
        ),
        migrations.AlterField(
            model_name='exhibitionmedia',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_media', to='home.room'),
        ),
    ]
