# Generated by Django 3.1.1 on 2020-09-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('home', '0028_auto_20200930_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='exhibition_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
