# Generated by Django 3.1.1 on 2020-10-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('home', '0029_room_exhibition_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionimage',
            name='soundbite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
