# Generated by Django 3.1.1 on 2020-10-01 20:23

from django.db import migrations


def move_default_images_to_soundbite_images(apps, schema_editor):
    WagtailImage = apps.get_model('wagtailimages', 'Image')
    SoundbiteImage = apps.get_model('home', 'SoundbiteImage')

    all_wagtail_images = WagtailImage.object.all().values()

    for wagtail_image in all_wagtail_images:
        soundbite_image = SoundbiteImage(**wagtail_image)
        soundbite_image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_soundbiteimage_soundbiteimagerendition'),
    ]

    operations = [
        migrations.RunPython(move_default_images_to_soundbite_images)
    ]
