# Generated by Django 3.1.1 on 2020-10-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20201001_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.soundbiteimage'),
        ),
        migrations.AlterField(
            model_name='artistimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.soundbiteimage'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='flyer_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.soundbiteimage'),
        ),
        migrations.AlterField(
            model_name='exhibitionimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.soundbiteimage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.soundbiteimage'),
        ),
        migrations.AlterField(
            model_name='workshopimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.soundbiteimage'),
        ),
    ]
