# Generated by Django 3.1.1 on 2020-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20201010_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundbiteimage',
            name='physical_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soundbiteimage',
            name='physical_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
